name: plasfora_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  image_picker: ^1.0.4
  file_picker: ^8.0.3

  lucide_icons: ^0.257.0
  chewie: ^1.7.0
  video_player: ^2.8.0
  google_fonts: ^6.2.1
  country_picker: ^2.0.20
  flutter_lucide: 1.6.2
  flutter_svg: ^2.0.7
  iconsax: 0.0.8
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  flutter_map: ^5.0.0
  latlong2: 0.9.1
  http: 1.4.0
  provider: ^6.0.5
  carousel_slider: ^5.1.1
  path_drawing: ^1.0.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/plasticSurgery/
    - assets/HairTransplant/hair-trans.png
    - assets/HairTransplant/
    - assets/IVF/
    - assets/healthy_holiday/
    - assets/acceuil/
    - assets/visit_tunisia/
